Codename=int(input("Enter your codename:"))
Real_Name =input("Enter your real name:")
Gadget=input("Enter your gadget:")
Mission_Location=input("Enter Mission Location:")
Operation_number=int(input("Enter the operation number:"))
print("**********************************")
print("   TOP SECRET - AGENT DOSSIER     ")
print("**********************************")
print()
print()
print(f"Codename: {Codename}")
print(f"Real Name: {Real_Name}")
print(f"Gadget: {Gadget}")
print()
print()
print("---------------------------------")
print("MISSION DETAILS:")
print(f"Operator ID: OP-{Operation_number}-{Codename}")
print(f"Location: {Mission_Location}")
print("----------------------------------")
print("   *** FOR YOUR EYES ONLY ***   "  ) 
print("**********************************")